CREATE TABLE [dbo].[Enrollments]
(
	[ProfessorId] INT NOT NULL,
	[DepartmentId] INT NOT NULL,
	[CourseId] INT NOT NULL,
	CONSTRAINT FK_EnrProfessor FOREIGN KEY ([ProfessorId]) REFERENCES Users(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_EnrDepartment FOREIGN KEY ([DepartmentId]) REFERENCES Departments(DepartmentId) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_EnrCourse FOREIGN KEY ([CourseId]) REFERENCES Courses(CourseId) ON UPDATE CASCADE ON DELETE CASCADE
)
